### ISSUE TITLE
Styling for Mobile App: Color Scheme, Font Choice

### ISSUE THREAD

**Issue by noormudassar** [cap-team-5/capstone-team-5#3]

**Comment by bjohnson122** [comment]
- [ ]  Helvetica (for smaller fonts/text body)
- [ ]  Bodoni Moda for headings 

Link below ⬇️

https://fonts.google.com/specimen/Bodoni+Moda?preview.text=New%20York%20is%20composed%20of%20five%20boroughs%20%E2%80%93%20Brooklyn,%20the%20Bronx,%20Manhattan,%20Queens%20and%20Staten%20Island%20-%20is%20home%20to%208.4%20million%20people%20who%20speak%20more%20than%20200%20languages,%20hail%20from%20every%20corner%20of%20the%20globe,%20and,%20together,%20are%20the%20heart%20and%20soul%20of%20the%20most%20dynamic%20city%20in%20the%20world.%20&preview.text_type=custom
